version: '4.0'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"