spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdietas?autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
