spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      schema: app_dietas
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    schemas: ${DB_SCHEMA:app_dietas}
    baselineOnMigrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: ${MAIL_SMTP_AUTH:true}
        starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
app-dietas:
  jwtSecret: ${JWT_SECRET:bxOksa8BHgdAhR80Y3pEYvS5M+MnF2sheFDqprkTqQ4odqoszJLW1ikw64/nT/dTvlgrcBTq7HfK1B9Gai2h5A==}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:900000}
